# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTkzYTk5YThhODI5MDVkYTIzOWRjYzE4YzEzN2VlNTQ3MWI2YTlmMDg0YWQyZmExYjBiZjM2MTliMDRhOWJmZWViZjUyMTNjYTEwNzZlNTY5MjA5ZGViNTE1MDUyODk2YjlmNmU1MzgyZmYwYjg3Mzc0NTg4YzhkNDFjMmVkYjc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
